name: "Run Gradle tasks"

on: pull_request

jobs:
  run-tasks:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare env
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        perl -pe "s/git\@github.com:/https:\/\/github.com\//g" -i scripts/commons4gradle.sh
        . $BASEDIR/arrow/scripts/commons4gradle.sh
        BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        sleep 180
        checkAndDownloadViaHTTPS arrow-core $BRANCH_NAME
        perl -pe "s/git pull//g" -i $BASEDIR/arrow-core/scripts/checkout-orchestrator.sh
        replaceGlobalPropertiesbyLocalConf $BASEDIR/arrow-core/gradle.properties
    - name: Build with local dependencies
      run: |
        cd $BASEDIR/arrow-core
        ./gradlew buildWithLocalDeps
    - name: Clean and prepare env
      run: |
        cd $BASEDIR/arrow-core
        git checkout .
        perl -pe "s/git pull//g" -i scripts/checkout-orchestrator.sh
        . $BASEDIR/arrow/scripts/commons4gradle.sh
        replaceGlobalPropertiesbyLocalConf gradle.properties
    - name: Build Doc with local dependencies
      run: |
        cd $BASEDIR/arrow-core
        ./gradlew buildArrowDocWithLocalDeps
