#!/bin/sh
git clone https://github.com/AlexPof/opycleid
git clone https://github.com/AlgebraicJulia/Catlab.jl
git clone https://github.com/Anton-Latukha/Fundamental-Haskell
git clone https://github.com/Bartor/funkcyjne
git clone https://github.com/CatalinMihaiGhita/libcat
git clone https://github.com/CategoricalData/CQL
git clone https://github.com/CategoricalData/catdb
git clone https://github.com/CategoricalData/opl
git clone https://github.com/Cobord/CategoriesOfOptics
git clone https://github.com/CompositionalPlanning/CompositionalPlanning
git clone https://github.com/DenizSt/TriCats
git clone https://github.com/Freshwood/scala-semigroup
git clone https://github.com/Insferatu/category-theory-dotty
git clone https://github.com/JasonShin/fp-core.rs
git clone https://github.com/KanHarI/CategoricalCpp
git clone https://github.com/KatagiriSo/RDCategoryWriter
git clone https://github.com/KatagiriSo/RDXYPicSupport
git clone https://github.com/Luteceo/CT-for-programmers
git clone https://github.com/Marceline/Undergrad
git clone https://github.com/Mircus/hyperstructures
git clone https://github.com/P3trur0/cattheo
git clone https://github.com/Risto-Stevcev/bastet
git clone https://github.com/Risto-Stevcev/bastet-async
git clone https://github.com/Risto-Stevcev/bastet-lwt
git clone https://github.com/Risto-Stevcev/bs-either
git clone https://github.com/Risto-Stevcev/bs-free
git clone https://github.com/Risto-Stevcev/category-theory-by-example
git clone https://github.com/Saityi/felis
git clone https://github.com/Sanjagh/santech-category-theory
git clone https://github.com/Shikanime/Realm
git clone https://github.com/SudipSinha/writings
git clone https://github.com/TOTBWF/cubical-categories
git clone https://github.com/TwoFX/EmbeddingTheorem
git clone https://github.com/Verites/verigraph
git clone https://github.com/YBogomolov/monadic-mondays
git clone https://github.com/ZheniaTrochun/category-theory
git clone https://github.com/aiya000/book-setulab-template
git clone https://github.com/aiya000/catamorphism-with-nico
git clone https://github.com/aiya000/setulabo-basic-category-proofs
git clone https://github.com/alf239/playground
git clone https://github.com/alhassy/CatsCheatSheet
git clone https://github.com/alohawav/naive_functional_programming
git clone https://github.com/amintimany/Categories
git clone https://github.com/arjunagu/yiming.github.io
git clone https://github.com/arquicanedo/graph2sheaves
git clone https://github.com/arrow-kt/arrow
git clone https://github.com/arrow-kt/arrow-media
git clone https://github.com/arthurxavierx/ebook-category-theory
git clone https://github.com/backwards-limited/scala-backwards
git clone https://github.com/barambani/laws
git clone https://github.com/bohadi/ctfp_notes
git clone https://github.com/bow-swift/bow
git clone https://github.com/burz/Feval
git clone https://github.com/butcherless/scala
git clone https://github.com/chadford/catsbook
git clone https://github.com/chakravala/AbstractTensors.jl
git clone https://github.com/chakravala/DirectSum.jl
git clone https://github.com/changlinli/answers-to-category-theory-for-programmers
git clone https://github.com/chriskevin/chrisunleashed
git clone https://github.com/copumpkin/categories
git clone https://github.com/damienstanton/ctrs
git clone https://github.com/danilkolikov/categories
git clone https://github.com/darrenjw/fps-course
git clone https://github.com/das-projects/Cheetah
git clone https://github.com/demystifyfp/FsToolkit.ErrorHandling
git clone https://github.com/dmitriz/functional-examples
git clone https://github.com/dogonthehorizon/seven-applied-cats
git clone https://github.com/elbaulp/Scala-Category-Theory
git clone https://github.com/epost/web-skdm
git clone https://github.com/err0r500/foundational-knowledge-for-programmers
git clone https://github.com/esapulkkinen/cifl-math-library
git clone https://github.com/fdilke/bewl
git clone https://github.com/felko/atl
git clone https://github.com/fosskers/ctfp
git clone https://github.com/fredefox/cat
git clone https://github.com/georgejkaye/circuit-visualiser
git clone https://github.com/gummif/categories
git clone https://github.com/gvolpe/split-morphism
git clone https://github.com/heades/dialectica-spaces
git clone https://github.com/heades/notes-on-fibrations
git clone https://github.com/hmemcpy/milewski-ctfp-pdf
git clone https://github.com/i-walker/arrow-docset
git clone https://github.com/i-walker/fp-ts-slides
git clone https://github.com/iamsurajgharat/category-theory-challenge-practice
git clone https://github.com/idris-industry/paradise
git clone https://github.com/isnullxbh/edu-category-theory
git clone https://github.com/ixaxaar/monoid.space
git clone https://github.com/jaalonso/Categorias_y_programacion
git clone https://github.com/jakebian/kan
git clone https://github.com/jameshaydon/smproc
git clone https://github.com/jarredbarber/Cat.jl
git clone https://github.com/jcouyang/meow
git clone https://github.com/jieyouxu/Category-Theory-Notes-CTFP
git clone https://github.com/jpfairbanks/SocialTheories.jl
git clone https://github.com/jpvillaisaza/abel
git clone https://github.com/jpvillaisaza/cain
git clone https://github.com/jreina/categories
git clone https://github.com/jwbuurlage/category-theory-programmers
git clone https://github.com/jwiegley/category-theory
git clone https://github.com/kammitama5/LambdaConf17-notes
git clone https://github.com/kayvank/frisby-study-guide
git clone https://github.com/kotlinz/kotlinz
git clone https://github.com/kykosic/pycats
git clone https://github.com/langston-barrett/reed-thesis
git clone https://github.com/laughedelic/M-Cohomology
git clone https://github.com/learn-fp/learn-fp
git clone https://github.com/leftaroundabout/explicit-constraint-lens
git clone https://github.com/lemastero/scala_typeclassopedia
git clone https://github.com/len/Domains
git clone https://github.com/liuxinyu95/unplugged
git clone https://github.com/ljbatwh/category-theory-for-programmers-js
git clone https://github.com/lubien/category-theory-for-programmers-solutions
git clone https://github.com/madkous/math490
git clone https://github.com/makarchuk/ctfp
git clone https://github.com/massimosiani/category-theory-for-programmers
git clone https://github.com/matteobaglini/functional-structures-refactoring-kata
git clone https://github.com/mduerig/hylo-quick
git clone https://github.com/mgechev/tscat
git clone https://github.com/mjendrusch/monoidal-categories-reboot
git clone https://github.com/mmenestret/fp-resources
git clone https://github.com/moodmosaic/bookmarks
git clone https://github.com/moosch/fp-maths-semigroups
git clone https://github.com/morishjs/haskell-playground
git clone https://github.com/mroman42/discokitty
git clone https://github.com/mroman42/introCategorias
git clone https://github.com/mroman42/optics-form-a-category
git clone https://github.com/mstn/cct-exercises
git clone https://github.com/mstn/duality
git clone https://github.com/mtumilowicz/java11-category-theory-kleisli-category
git clone https://github.com/mtumilowicz/java11-category-theory-poset-product
git clone https://github.com/mtumilowicz/java11-category-theory-powerset-poset-product
git clone https://github.com/mtumilowicz/java11-category-theory-reader-functor
git clone https://github.com/mtumilowicz/java11-category-theory-set-coproduct
git clone https://github.com/mtumilowicz/java11-category-theory-set-product
git clone https://github.com/mtumilowicz/java11-category-theory-total-poset-product
git clone https://github.com/mtumilowicz/scala212-category-theory-const-functor
git clone https://github.com/mtumilowicz/scala212-category-theory-either-bifunctor
git clone https://github.com/mtumilowicz/scala212-category-theory-set-initial-terminal-objects
git clone https://github.com/mtumilowicz/scala212-category-theory-set-semiring
git clone https://github.com/mtumilowicz/scala212-cats-category-theory-composing-functors
git clone https://github.com/neko-kai/fp-dictionary
git clone https://github.com/neshkeev/avaj
git clone https://github.com/otaviopace/teoria-das-categorias-ufabc
git clone https://github.com/oxford-quantum-group/discopy
git clone https://github.com/paolobrasolin/commutative-diagrams
git clone https://github.com/pawelrubin/Programowanie-funkcyjne
git clone https://github.com/peter-vilja/pure-ct
git clone https://github.com/pgabara/scala-with-cats
git clone https://github.com/philzook58/ad-lens
git clone https://github.com/philzook58/not-bad-ccc
git clone https://github.com/pindaroso/software-foundations
git clone https://github.com/politrons/LetsGO
git clone https://github.com/pravin-raha/category-theory-for-programmers-scala
git clone https://github.com/premshree/monads-typescript
git clone https://github.com/rcardin/cat-notebook
git clone https://github.com/relrod/ct
git clone https://github.com/rkoeninger/KitchenSink
git clone https://github.com/rpeszek/notes-milewski-ctfp-hs
git clone https://github.com/ruippeixotog/intro-to-category-theory
git clone https://github.com/rvarago/kitten
git clone https://github.com/rwols/MasterThesis
git clone https://github.com/sblack4/category-theory-for-programmers-in-scala
git clone https://github.com/sderosiaux/every-single-day-i-tldr
git clone https://github.com/sellout/category-parametric-talk
git clone https://github.com/sellout/caterwaul
git clone https://github.com/sellout/cheshire
git clone https://github.com/sellout/dog
git clone https://github.com/sellout/haskerwaul
git clone https://github.com/sharkdp/purescript-ctprelude
git clone https://github.com/sjoerdvisscher/data-category
git clone https://github.com/sjoerdvisscher/free-functors
git clone https://github.com/spidermoy/Monads_KleisliTriples_Proof
git clone https://github.com/spiral-lang/spiral
git clone https://github.com/spl/basic-category-theory
git clone https://github.com/srghma/category-theory-bartosz-milewski-lecture-notes
git clone https://github.com/stanfordhaskell/cs43
git clone https://github.com/statebox/awesome-applied-ct
git clone https://github.com/statebox/cql
git clone https://github.com/statebox/fsm-oracle
git clone https://github.com/statebox/idris-ct
git clone https://github.com/stephen-lazaro/persians
git clone https://github.com/steshaw/plt
git clone https://github.com/surovv/kleisli
git clone https://github.com/tah0/ct4s
git clone https://github.com/themadteaparty/aluffi
git clone https://github.com/thma/LtuPatternFactory
git clone https://github.com/tlareg/FP
git clone https://github.com/turbaszek/ct4cs
git clone https://github.com/turbaszek/haskell-labs
git clone https://github.com/typedefs/site
git clone https://github.com/typedefs/typedefs
git clone https://github.com/uncomplicate/fluokitten
git clone https://github.com/varkor/quiver
git clone https://github.com/verimath/termination
git clone https://github.com/victorqrt/ctfp_challenges
git clone https://github.com/vinsis/applied-category-theory-slides
git clone https://github.com/vishallama/algebra-chapter0
git clone https://github.com/vishallama/categories-and-categorical-logic
git clone https://github.com/vishallama/frdomain
git clone https://github.com/westerbaan/theses
git clone https://github.com/wetneb/sheetshow
git clone https://github.com/wezm/category-theory
git clone https://github.com/williamareynolds/ts-cat
git clone https://github.com/wkolowski/CoqCat
git clone https://github.com/wkolowski/Seminar-Bisimulation-and-Coinduction
git clone https://github.com/wonks/type-theory-reading-group
git clone https://github.com/xieyuheng/cat
git clone https://github.com/yishn/jsx-tikzcd
git clone https://github.com/yishn/tikzcd-editor
git clone https://github.com/yurrriq/frege-cats
git clone https://github.com/yurrriq/notes
