language: scala

sudo: false

install:
  - pip install --user codecov

language: scala
  
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.4
  - 2.13.0-M5

jdk:
  - oraclejdk8

script:
  - scripts/travis-publish.sh

cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  
before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c5bebf7d686684123f55
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
    - secure: "f5Qe6G628ry7Hiq60mSgwEtmM61sXOM65kgQX/D6V/h2ZhztOgZS5+aiCaooN9KKy/kJ1tXF5rx+OisBvZ6bnBrLD0EFFSuj2HkWOp6Yv+jTUyZ6+3TrRBXciDS1taoSUIbi2Kui42fnSMs+MsrLaL4iWzcOBIhYpihA973nrOwNFHyqHX8uE34v+7bzNgqnni/CibAyA6OnPckwNE3B+mSc5cvP+Yfmvo6uq0VwwiaFAQtfSOMUJ+jzizkqnqUawRVVeUo3CJ4bZE6MzSTvAgRBexxPgyGX3gE46a8MPmjw+RnrJiUiCwKCOk1rm7NspoQQmNdbVliIzRYlQChHyiTvRWiBrRfSN3+09GSonDx6C4U40hOng/GNu3VbXNXAtJQkLKMyik9DFCXlByrG+B3HZcds+22eGj4kCGCR+ZshOn/J2FEFSubHmM4ZSETkBena/Ahkglb6un4KGIfNumSBAYTF5Ob2x+bbMAGuaLc2gpTdRCxI+e3XTZFsb3dBZfrzJwcGPzxGmuNHYQfWi83zeQUAmoaIxnlvUdL9ph4AWZbLkxFAVd2D/E8pcosva7WyCaARj/HPhXD6uKElXyjUgp0eLCviMf4EKtHvj53c8rwv8rlwbxgJ1KESlp76bpZmHPhA8Y0Ly4T+Hnjdp5wLawpPTCKe0p7Ox/u4+Zg="
    - secure: "J4t3t64LOm15LxJyMQDlth2A69rTOzy28jHEIgmPtjGwFm8nlqncqEC3QazJJhjWJPw3tIi4EFV5SzGn3+/26Dcd8EbVYnZgTd9w4FtpuPSWHM2WTKWvIbD0D0MSenNg7tbjYh5jQ22DSWkderVi9UiLO0MzYvXdZwhJ+VSRorQLr5deoQN/+nmJdPq9GTD4Brv4CdI8Lolg9up7o4ZXv/4dgddIeUjDXqynXNF+Em8ty0VI1paKN6hW5/1DGQJfMYJpGsPZnP4qdHa+KDBN7853OogzzWs6FE/OsnazpepPJrmKEQFf2RQYOY28U6N0OmiXcDvVDkLj7rdcPy20nC59Cazcwdyd6XchGVOvv13hABG6pYts18cbh+b/BNJlM5aeCxjrgOU3wN2B9rwgNyTTwUYkCK/nN3jHUx9e2itLb+pEv5Ng+ldccZMNFElrbKdDdVBjynGwyMG65oPoYi2bhYBS3Wrfhog2OnKMbw6VEucNvz8URIqMqurCK1RvKxNM/9pvNRZ40OkPJXQ2zG+btDsGuTa/HHj7dlp7DSc7H7pw008cMtY+Wjq83C3sWi662DcuP/fm8K/Ys+My8pjdX47J3AYKnq46jPAS0Rn4jUTmq7nOy/zAE+sv9nlNN8FWoTFFju6IsCxrSoCp8LHJcXGOtN6qs2yQ7NBnH0E="
