before_install:
 - sudo apt-get install ghostscript

install:
 - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

jobs:
  include:
    - if: NOT tag IS present
      script: l3build check -q -H --show-log-on-error
      name: "Test suite"
    - if: NOT tag IS present
      script: l3build doc -q -H --show-log-on-error
      name: "Documentation"
    - if: tag IS present
      script: l3build ctan -H --show-log-on-error
      name: "Full CTAN build"

notifications:
  email:
    recipients:
      - latex3-commits@tug.org
    on_success: change
    on_failure: always
    on_start:   never

deploy:
  - provider: releases
    api_key:
       secure: WBQQ1qyLWE9O1DmCAIZUrM7x9nfqNbHzOyhbb8SWykPkCPX/wHcDge9NcLnnxqI8AZS7VUPjC2h5uCnr6WmI23tTn6LDentXIlsKP83jMO6/8Ijm0Zns75+WMsQBkWhnHRrx55ophhk88ay6BSTjkR0P9Sm/oub7U1YSMLbvSqacai/ETbbG2S2wDsnKqiXkX5qP/gP+06zs1X9WZL3rTkNkfuSVsyQpLOmSOO/zSjOrxh4caHKfhwlKTe6K0pxfdhW2wfpky8ufFV8DdLxvtG4kOahsvdLSsC6vrnxZ9bqEH4mXxoy63/R4kev5dbpF4tWRF9Uvidxg0ru6LBv7AP0IH7ZoYR8L9/QYruSoDxaNRlBdRpWlYjZS58bgtwRjk6CfABk2M3Me2DP4VL5yHo4C6RNf0zxgD0WbEmZcrV8PJastvHwOHj6IlIDUp2jUzRNmDLbHegj4EKYv7JeBSkGgNkGJAK8QZcwEY8ngHOaqVQ0Y6cX5gPN1p64LkQrtxJTbgRgUAMlGxIQImIxu7L+adV0ShxQlzmmEGoB4D2Pl0/WVqTMKJ2MkhDTOBM4isYsu/6uq/BI1mOu+Ann4betmp1czNfTbYE0derTd3d1BHKF+kULOk+nCIZPsPvy+GRUzjCa43pnd3aDPz3HLFORQ+apgRXz1+rUCuhfl9N8=
    file_glob: true
    file:
      - ./*.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG == dev-*
    prerelease: true
  - provider: releases
    api_key:
      secure: WBQQ1qyLWE9O1DmCAIZUrM7x9nfqNbHzOyhbb8SWykPkCPX/wHcDge9NcLnnxqI8AZS7VUPjC2h5uCnr6WmI23tTn6LDentXIlsKP83jMO6/8Ijm0Zns75+WMsQBkWhnHRrx55ophhk88ay6BSTjkR0P9Sm/oub7U1YSMLbvSqacai/ETbbG2S2wDsnKqiXkX5qP/gP+06zs1X9WZL3rTkNkfuSVsyQpLOmSOO/zSjOrxh4caHKfhwlKTe6K0pxfdhW2wfpky8ufFV8DdLxvtG4kOahsvdLSsC6vrnxZ9bqEH4mXxoy63/R4kev5dbpF4tWRF9Uvidxg0ru6LBv7AP0IH7ZoYR8L9/QYruSoDxaNRlBdRpWlYjZS58bgtwRjk6CfABk2M3Me2DP4VL5yHo4C6RNf0zxgD0WbEmZcrV8PJastvHwOHj6IlIDUp2jUzRNmDLbHegj4EKYv7JeBSkGgNkGJAK8QZcwEY8ngHOaqVQ0Y6cX5gPN1p64LkQrtxJTbgRgUAMlGxIQImIxu7L+adV0ShxQlzmmEGoB4D2Pl0/WVqTMKJ2MkhDTOBM4isYsu/6uq/BI1mOu+Ann4betmp1czNfTbYE0derTd3d1BHKF+kULOk+nCIZPsPvy+GRUzjCa43pnd3aDPz3HLFORQ+apgRXz1+rUCuhfl9N8=
    file_glob: true
    file:
      - ./*.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG != dev-*
    prerelease: false
